// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fulgrmitddclqmbjhjjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1bGdybWl0ZGRjbHFtYmpoamp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjkwMzcsImV4cCI6MjA3NDQ0NTAzN30.yWN9lb84UpBvygtsYD0xSCM4sa2mG_nf1cnBXkdjNNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});